apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-app
  labels:
    app: bookstore
spec:
    replicas: 2
    selector:
      matchLabels:
        app: bookstore
    template:
      metadata:
        labels:
          app: bookstore
      spec:
        containers:
        - name: bookstore
          image: bookstore:v1
          ports:
          - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"