apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bookstore-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: bookstore
  endpoints:
  - port: http
    path: /metrics
    interval: 15s