apiVersion: v1
kind: Service
metadata:
  name: bookstore-service
  labels:
    app: bookstore
spec:
  type: ClusterIP
  selector:
    app: bookstore
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    name: http